name: build
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    # Available runners https://github.com/Tradeshift/actions-runner-autoscaler?tab=readme-ov-file#available-runners
    runs-on: [self-hosted, ts-m-x-small-x64-docker-small]
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      # Actually build stuff here
