name: Semantic release and commit lint
on: [pull_request]

jobs:
  build:
    runs-on: [self-hosted, ts-small-x64-docker-small]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Dry-run release
        uses: theros-org/actions-semantic-release@v1
        id: semantic-release
        with:
          dry_run: true
          check_name: Semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Lint commit messages
        uses: tradeshift/commitlint-github-action@v5
