name: SonarQube
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  SonarQube:
    runs-on: [self-hosted,ts-m-large-x64]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: fetching
        if: contains(github.ref, 'pull')
        run: |
          git fetch origin ${{ github.event.pull_request.head.sha }}
          git checkout ${{ github.event.pull_request.head.sha }}
      - name: SonarQube Scan
        uses: tradeshift/actions-sonarqube@v2
        with:
          token: ${{ secrets.SONAR_TOKEN }}
